name: CyanogenMod Building
on: 
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/**'
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Space Pre
        run: |
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
      - name: Install and uninstall packages
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo snap remove --purge lxd
          sudo snap remove --purge core20
          sudo snap remove --purge snapd
          sudo -E apt -y autoremove --purge snapd
          sudo sh -c "echo Package: snapd > /etc/apt/preferences.d/nosnap.pref"
          sudo sh -c "echo Pin: release a=* >> /etc/apt/preferences.d/nosnap.pref"
          sudo sh -c "echo Pin-Priority: -10 >> /etc/apt/preferences.d/nosnap.pref"
          sudo -E sh -c "apt autoremove -y --purge google* azure* ruby* php* apache* aspnet* cloud-* dbus dotnet* firebird* firefox* llvm* moby* mongodb* mono* msbuild* mssql* mysql* nginx* perl* postgresql* powershell* r-* rpm* x11* xserver* *-icon-theme git-* grub* gsettings* python3* *jdk* 2> /dev/null" || true
          sudo -E apt-get update
          sudo -E apt install bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev wget tree -y
          curl https://cdn.azul.com/zulu/bin/zulu7.56.0.11-ca-jdk7.0.352-linux_amd64.deb > openjdk7.deb
          sudo -E dpkg -i openjdk7.deb || true
          rm openjdk7.deb
          sudo -E apt install -f
          sudo rm -f /usr/bin/python
          sudo ln -s /bin/python2.7 /usr/bin/python
          sudo -E apt-get clean
          sudo rm -rf /usr/local/lib/heroku /usr/local/lib/node_modules /usr/local/lib/android /usr/local/share/chromium /usr/share/dotnet /usr/local/share/phantomjs* /usr/local/share/*driver /usr/local/share/vcpkg /etc/mysql /etc/php /etc/skel /etc/apt/sources.list.d ~/.dotnet ~/runners/*.tgz
          sudo sh -c "curl https://storage.googleapis.com/git-repo-downloads/repo > /usr/bin/repo"
          sudo chmod a+x /usr/bin/repo
          
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 64
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-haskell: 'true'
          remove-android: 'true'
              
      - name: Pull codes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "Github Action"
          mkdir lineage
          cd lineage
          repo init --depth=1 -u https://github.com/LineageOS/android.git -b cm-12.1
          repo sync -c -f --no-tags --no-clone-bundle -j 16
          git clone https://github.com/Jakesoso/android_device_oppo_A37.git -b cm12.1 --depth=1 device/oppo/A37
          git clone https://github.com/peasoft/android_vendor_oppo_A37.git --depth=1 vendor/oppo/A37
          find . -name ".git"  | xargs rm -rf
          rm -rf .repo
          rm -rf device/oppo/A37/README.md
        shell: bash
        
      - name: Space Post
        run: |
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
      
#      - name : Upload Logs
#        uses: actions/upload-artifact@master
#        with:
#          name: lineageos-source-tree
#          path: lineage/treelog
      
      - name: Build CyanogenMod OS
        run: |
          false
          cd lineage
          sh device/oppo/A37/patches/install.sh
          source build/envsetup.sh
          lunch cm_A37-user
          export ANDROID_JAVA_TOOLCHAIN="/usr/lib/jvm/java-8-openjdk-amd64/bin"
          export JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"
          export JAVA_HOME_8_X64="/usr/lib/jvm/java-8-openjdk-amd64"
          unset JAVA_HOME_11_X64
          unset JAVA_HOME_17_X64
          make
      
      - name: Debug
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
          
      - name : Upload ROM
        uses: actions/upload-artifact@master
        with:
          name: cm-build-oppo-A37
          path: lineage/out